config/routes.rb
# Rails.application.routes.default_url_options[:host] = Rails.application.credentials[:development][:hostname]

Rails.application.routes.draw do
  require 'sidekiq/web'
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/  do
    devise_for :managers, path: 'manager',
      controllers: { sessions: 'managers/sessions' },
      path_names: { sign_in: 'login', sign_out: 'logout' }

    namespace :manager do
      authenticate :manager do
        mount Sidekiq::Web => '/sidekiq'
      end
      root 'dashboard#index'
      get :dashboard, to: 'dashboard#index'
      get :chart_statistics, to: 'dashboard#chart_statistics'
      resources :products do
        member do
          get 'change_appearance'
          get 'archive'
          get 'remove_single_image'
        end
        collection do
          get :archival
        end
      end
      resources :orders, only:[:index, :show, :update]
      resources :categories do
        member do
          get 'change_appearance'
        end
      end
      resources :users, only:[:index, :show]
      resources :discounts do
        member do
          get 'change_appearance'
          get 'edit_products'
          put 'update_products'
        end
      end
      resources :contacts, except: [:show]
    end

    root 'store#index', as: 'store'
    resources :line_items, only:[:create, :destroy, :update]
    resources :products, only: [:show]
    get 'category/:category', to: 'products#index', as: 'category_products'

    get   :cart,      to: 'carts#show'
    get   :order,     to: 'orders#new',               as: 'new_order'
    post  :order,     to: 'orders#create',            as: 'orders'
    get   :client,    to: 'users#new',                as: 'new_user'
    post  :client,    to: 'users#create',             as: 'users'
    get   :info,      to: 'user_informations#new',    as: 'new_user_information'
    post  :info,      to: 'user_informations#create', as: 'user_informations'
    get   :contacts,  to: 'store#contacts',           as: 'store_contacts'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/discount.rb
class Discount < ApplicationRecord
  has_many :products

  validates_presence_of :title, :value
  validates :value, numericality: { greater_than: 0, less_than: 100 }

  def actual
    if start_at && end_at
      Time.now.between? start_at, end_at
    elsif start_at || end_at
      start_at < Time.now if start_at
      end_at > Time.now if end_at
    else
      true
    end
  end
end

app/controllers/manager/categories_controller.rb
class Manager::CategoriesController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_category_present, only: [:edit, :update, :destroy, :change_appearance]
  before_action :_set_category_orders, only: [:edit, :destroy]
  layout 'managers/dashboard'

  def index
    _set_categories
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new _permitted_category_params

    respond_to do |format|
      if @category.save
        format.html { redirect_to edit_manager_category_path(@category), notice: t('manager.categories.flash.create.success') }
      else
        format.html { render :new }
        flash.now.notice = t('manager.categories.flash.create.failure')
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update _permitted_category_params
        format.html { redirect_to manager_categories_path, notice: t('manager.categories.flash.update.success') }
      else
        format.html { render :edit }
        flash.now.notice = t('manager.categories.flash.update.failure')
      end
    end
  end

  def destroy
    respond_to do |format|
      if @category_orders.empty?
        notice =
          if @category.destroy
            t('manager.categories.flash.destroy.success')
          else
            t('manager.categories.flash.destroy.failure')
          end
        format.html { redirect_to manager_categories_path, notice: notice }
        format.js
      else
        format.html { redirect_to manager_categories_path, notice: t('manager.categories.flash.destroy.involvement') }
      end
    end
  end

  def change_appearance
    respond_to do |format|
      if @category.update visible: !@category.visible
        notice =
          if @category.visible
            t('manager.categories.flash.change_appearance.visible')
          else
            t('manager.categories.flash.change_appearance.invisible')
          end
        format.html { redirect_to manager_categories_path, notice: notice  }
      else
        format.html { redirect_to manager_categories_path, notice: t('manager.categories.flash.change_appearance.failure') }
      end
    end
  end

  private

  def _set_category
    @category = Category.find_by_id params[:id]
  end

  def _ensure_category_present
    redirect_to manager_categories_path unless params[:id].present? && _set_category
  end

  def _set_categories
    @categories = Category.all
  end

  def _set_category_orders
    @category_orders = Order.find(LineItem.where(product_id: @category.products.ids).map(&:order_id))
  end

  def _permitted_category_params
    params.require(:category).permit(:title, :slug, :image, translations_attributes: [:id, :attribute_name, :locale, :value])
  end
end

app/controllers/manager/contacts_controller.rb
class Manager::ContactsController < ApplicationController
  before_action :authenticate_manager!
  before_action :_set_contact, only: [:edit, :update, :destroy, :create]

  layout 'managers/dashboard'

  def index
    @contacts = {}
    Contact.kinds.keys.each { |kind| @contacts[kind] = Contact.public_send kind }
  end

  def new
    @contact = Contact.new
  end

  def edit; end

  def create
    @contact = Contact.new _permitted_contact_params
    respond_to do |format|
      if @contact.save
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.create.success') }
      else
        format.html { render :new }
        flash.now.notice = t('manager.contacts.flash.create.failure')
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update _permitted_contact_params
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.update.success') }
      else
        format.html { render :edit }
        flash.now.notice = t('manager.contacts.flash.update.failure')
      end
    end
  end

  def destroy
    respond_to do |format|
      if @contact.destroy
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.destroy.success') }
      else
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.destroy.failure') }
      end
    end
  end

  private

  def _set_contact
    @contact = Contact.find_by_id params[:id]
  end

  def _permitted_contact_params
    params.require(:contact).permit(:kind, :value, :social_type)
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < ApplicationController
  before_action :authenticate_manager!
  layout 'managers/dashboard'

  def index
    _get_products
    _get_orders
    _get_categories
  end

  def chart_statistics
    render json: { line: SetLineChart.run!, donut: SetDonutChart.run! }
  end

  private

  def _get_products
    outcome = GetScopeStat.run scopes: [:visible, :hidden],
                               model: Product,
                               scope_for_total: :relevant
    @products = outcome.valid? ? outcome.result : nil
  end

  def _get_orders
    outcome = GetScopeStat.run scopes: Order.statuses.keys.map(&:to_sym),
                               model: Order
    @orders = outcome.valid? ? outcome.result : nil
  end

  def _get_categories
    outcome = GetCategoriesStat.run
    @categories = outcome.valid? ? outcome.result : nil
  end

end

app/controllers/manager/discounts_controller.rb
class Manager::DiscountsController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_discount_present, except: [:index, :new, :create]
  layout 'managers/dashboard'

  def index
    @discounts = Discount.all.page params[:page]
  end

  def show; end

  def new
    @discount = Discount.new
  end

  def edit; end

  def create
    @discount = Discount.new _permitted_discount_params
    respond_to do |format|
      if @discount.save
        format.html { redirect_to manager_discounts_path, notice: t('manager.discounts.flash.create.success') }
      else
        flash.now.notice = t('manager.discounts.flash.create.failure')
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @discount.update _permitted_discount_params
        format.html { redirect_to manager_discount_path(@discount), notice: t('manager.discounts.flash.update.success') }
      else
        flash.now.notice = t 'manager.discounts.flash.update.failure'
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @discount.products.blank?
        notice =
          if @discount.destroy
            t('manager.discounts.flash.destroy.success')
          else
            t('manager.discounts.flash.destroy.failure')
          end
        format.html { redirect_to manager_discounts_path, notice: notice }
      else
        format.html { redirect_to manager_discount_path(@discount), notice: t('manager.discounts.flash.destroy.involvement') }
      end
    end
  end

  def change_appearance
    respond_to do |format|
      notice =
        if @discount.actual && @discount.update(start_at: nil, end_at: Time.now)
          t('manager.discounts.flash.change_appearance.invisible')
        elsif !@discount.actual && @discount.update(start_at: nil, end_at: nil)
          t('manager.discounts.flash.change_appearance.visible')
        else
          t('manager.discounts.flash.change_appearance.failure')
        end
      format.html { redirect_to manager_discount_path(@discount), notice: notice }
    end
  end

  def edit_products
    @products = Product.relevant.page params[:page]
  end

  def update_products
    if @discount.products.present?
      Product.where(id: @discount.products.ids - [*params[:product_ids]]).update_all(discount_id: nil)
    end
    Product.where(id: params[:product_ids]).update_all(discount_id: @discount.id)
    redirect_to edit_products_manager_discount_path
  end

  private

  def _ensure_discount_present
    @discount = Discount.find_by(id: params[:id])
    redirect_to manager_discounts_path unless @discount
  end

  def _permitted_discount_params
    params.require(:discount).permit(:title, :description, :value, :start_at, :end_at)
  end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_order_present, only: [:show, :update]
  layout 'managers/dashboard'

  def index
    if params[:status].present? && Order.statuses.keys.exclude?(params[:status])
      redirect_to manager_orders_path, notice: t('manager.orders.flash.index.prohibited')
    else
      @current_status = params[:status]
      @orders = Order.filter(_filtering_params)
                     .search_by_name_or_email_or_telephone(params[:search_query])
                     .page params[:page]
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def show; end

  def update
    respond_to do |format|
      if @order.update _permitted_order_params
        OrderMailer.manager_information(@order).deliver
        OrderMailer.client_confirmation(@order).deliver if params[:notification]
        format.html do
          redirect_to manager_orders_path(status: _permitted_order_params[:status]),
                      notice: t('manager.orders.flash.update.success')
        end
      else
        flash.now.notice = t('manager.orders.flash.update.failure')
        format.html { render :edit }
      end
    end
  end

  private

  def _ensure_order_present
    @order = Order.includes(:products).find_by(id: params[:id])
    redirect_to manager_order_path unless @order
  end

  def _permitted_order_params
    params.require(:order).permit(:title, :description, :image, :price, :status)
  end

  def _filtering_params
    params.slice(:status)
  end

end

app/controllers/manager/users_controller.rb
class Manager::UsersController < ApplicationController
  before_action :authenticate_manager!
  layout 'managers/dashboard'

  def index
    @users = User.search_by_name_or_email_or_telephone(params[:search_query]).page params[:page]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    redirect_to users_path unless @user
  end

end

app/controllers/managers/confirmations_controller.rb
class Managers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/managers/omniauth_callbacks_controller.rb
class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/managers/passwords_controller.rb
class Managers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/unlocks_controller.rb
class Managers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/manager_helper.rb
module ManagerHelper

  def current_page_name
    controller.controller_name.split("_").join(" ")
  end

  def nav_link link_text, link_path, icons_class = '', method = :get
    class_name = current_page?(link_path) ? 'active' : ''
    link_class = icons_class.blank? ? '' : 'nav-label'
    content_tag :li, class: class_name do
      concat (
        link_to link_path, method: method do
          concat content_tag :i, '', class: icons_class if icons_class.present?
          concat content_tag :span, link_text, class: link_class
        end
      )
    end
  end

  def group_link link_text, controller, icons_class, &block
    class_name = params[:controller].delete('/').start_with?(controller.delete('/')) ? 'active' : ''
    content_tag :li, class: class_name do
      concat (
        link_to url_for(controller: controller, action: 'index') do
          concat content_tag :i, '', class: icons_class
          concat content_tag :span, link_text, class: 'nav-label'
          concat content_tag :span, '', class: 'fa arrow'
        end
      )
      block.call if block_given?
    end
  end

  def orders_status_links
    links_hash = {}
    Order.statuses.keys.each { |status| links_hash[status] = manager_orders_path(status: status) }
    links_hash
  end

  def pending_orders_counter
    Order.where(status: 'pending').count
  end


  def collapse_button button_title, button_class, target_id, target, &block
    concat button_tag button_title, class: button_class, data: { toggle: "collapse", target: "##{target_id}" }
    concat content_tag :br
    content_tag :ul, id: target_id, class: "list-group collapse" do
      target.each do |item|
        concat (
          content_tag :li, class: "list-group-item" do
            yield item
          end
        )
      end
    end
  end

  def time_delay created_at
    time_ago_in_words(Time.now - (Time.now - created_at.to_time).seconds)
  end
end

app/views/manager/discounts/_discount.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox product-detail">
        <div class="ibox-content">
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
              <h2 class="font-bold m-b-xs"> <%= @discount.title %> </h2>
              <div class="m-t-md">
                <h2 class="product-main-price">
                  <%= number_to_percentage @discount.value, precision: 0  %>
                </h2>
              </div>

              <hr>
              <h4><%= t 'manager.layout.schedule' %></h4>

              <div class="small text-muted">
                <%= t('activerecord.attributes.discount.start_at') %>:
                <%= @discount.start_at ? @discount.start_at.strftime("%d.%m.%Y") : t('manager.layout.always')%>
                <%= t 'activerecord.attributes.discount.end_at' %>:
                <%= @discount.end_at ? @discount.end_at.strftime("%d.%m.%Y %H:%M:%S") : t('manager.layout.never')%>
              </div>

              <hr>

              <h4><%= t 'activerecord.attributes.discount.description' %></h4>

              <div class="small text-muted">
                <%= @discount.description %>
              </div>

              <hr>

              <h4><%= t 'manager.layout.products' %></h4>
              <div class="small text-muted">
                <% if @discount.products.present?  %>
                  <%= collapse_button t('manager.layout.show'),
                    "btn btn-xs btn-outline btn-primary",
                    "products-list",
                    @discount.products do |item| %>
                      <%= link_to item.title, manager_product_path(item) %>
                  <% end %>
                <% else %>
                  <p><%= t 'manager.layout.none' %></p>
                <% end %>
              </div>

              <div>
                <hr>
                <div class="btn-group">
                  <% if @discount.actual %>
                    <%= link_to t('manager.layout.deactivate'), change_appearance_manager_discount_path(@discount),
                      class: "btn btn-warning btn-sm",
                      data: { confirm: t('manager.discounts.confirm.activate')} %>
                  <% else  %>
                    <%= link_to t('manager.layout.activate'),change_appearance_manager_discount_path(@discount),
                      class: "btn btn-primary btn-sm",
                      data: { confirm: t('manager.discounts.confirm.deactivate')} %>
                  <% end  %>
                </div>
                <div class="btn-group">
                  <%= link_to t('manager.layout.products'), edit_products_manager_discount_path(@discount),
                    class: "btn btn-primary btn-sm"%>
                </div>
                <div class="btn-group">
                  <%= link_to t('manager.layout.edit'), edit_manager_discount_path(@discount),
                    class: "btn btn-primary btn-sm pull-right"%>
                </div>
                <div class="btn-group">
                  <%= link_to t('manager.layout.delete'), manager_discount_path(@discount),
                    class: "btn btn-danger btn-sm pull-right",
                    method: "delete",
                    data: { confirm: t('manager.discounts.confirm.delete')} %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/discounts/_form.html.erb
<%= form_for [:manager, @discount] do |form| %>
  <% if @discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= t 'activerecord.errors.messages.record_invalid', errors: @discount.errors.count  %></h2>
      <ul>
        <% @discount.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox product-detail">
          <div class="ibox-content">
            <fieldset class="form-horizontal">

              <div class="field">
                <div class="form-group">
                  <%= form.label :title, class:"col-sm-2 col-lg-1 control-label" %>
                  <div class="col-sm-10 col-lg-11">
                    <%= form.text_field :title, id: :discount_title,
                      placeholder: t('activerecord.attributes.discount.title'),
                      class:"form-control",
                      required: true %>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <%= form.label :value, class:"col-sm-2 col-lg-1 control-label" %>
                <div class="col-sm-10 col-lg-11">
                  <%= form.number_field :value,
                    id: :discount_value,
                    placeholder: t('activerecord.attributes.discount.value'),
                    class:"form-control",
                    min: 1,
                    max: 99,
                    required: true %>
                </div>
              </div>



              <div class="form-group">
                <%= form.label :description, class:"col-sm-2 col-lg-1 control-label" %>
                <div class="col-sm-10 col-lg-11">
                  <%= form.text_area :description,
                    id: :discount_description,
                    placeholder: t('activerecord.attributes.discount.description'),
                    class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= form.label :start_at, class:"col-sm-2 col-lg-1 control-label" %>
                <div class="col-sm-10 col-lg-11">
                  <%= form.text_field :start_at,
                    id: :discount_start_at,
                    class: "form-control date-time",
                    placeholder: "dd/mm/yyyy hh:mm"%>
                </div>
              </div>

              <div class="form-group">
                <%= form.label :end_at, class:"col-sm-2 col-lg-1 control-label" %>
                <div class="col-sm-10 col-lg-11">
                  <%= form.text_field :end_at,
                    id: :discount_end_at,
                    class: "form-control date-time",
                    placeholder: "dd/mm/yyyy hh:mm" %>
                </div>
              </div>

            </fieldset>

            <br>

            <div class="row">
              <div class="col-lg-12">
                <div class="form-group">
                  <%= form.submit class: "btn btn-primary pull-right" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/manager/discounts/_list.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="ibox">
      <div class="ibox-content">
        <% if @discounts.present? %>
          <div class="form-group">
            <table class="table table-hover table-stripped toggle-arrow-tiny" id="discounts-table">
              <thead>
                <tr>
                  <th><%= t('activerecord.attributes.discount.title') %></th>
                  <th><%= t('activerecord.attributes.discount.value') %></th>
                  <th class="hidden-xs"><%= t 'activerecord.attributes.discount.start_at' %></th>
                  <th class="hidden-xs"><%= t 'activerecord.attributes.discount.end_at' %></th>
                  <th class="hidden-xs"><%= t 'manager.layout.products'%></th>
                  <th class="text-center"><%= t 'manager.layout.active'%></th>
                </tr>
              </thead>
              <tbody>
                <% @discounts.each do |discount|  %>
                  <tr data-link= "<%= manager_discount_path(discount) %>" class="selectable-row">
                    <td><%= discount.title %></td>
                    <td><%= number_to_percentage discount.value, precision: 0 %></td>
                    <td class="hidden-xs"><%= discount.start_at ? discount.start_at.strftime("%d.%m.%Y") : t('manager.layout.always')%></td>
                    <td class="hidden-xs"><%= discount.end_at ? discount.end_at.strftime("%d.%m.%Y") : t('manager.layout.never')%></td>
                    <td class="hidden-xs"><%= discount.products.count%></td>
                    <td class="unselectable">
                      <%= link_to manager_discount_path(discount) do %>
                        <% if discount.actual %>
                          <span class="label label-success col-xs-12 col-sm-12"><%= t "manager.layout.#{discount.actual}_yes" %></span>
                        <% else %>
                          <span class="label label-warning col-xs-12 col-sm-12"><%= t "manager.layout.#{discount.actual}_no" %></span>
                        <% end  %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <div class="text-center">
              <%= paginate @discounts %>
            </div>
          </div>
        <% else %>
          <div class="text-center">
            <h2><%= t 'manager.layout.no_information' %></h2>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/manager/discounts/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t("manager.layout.#{current_page_name}") %></h2>
    <ol class="breadcrumb">
      <li>
        <%= t("manager.layout.#{current_page_name}") %>
      </li>
      <li><b><%= t('manager.layout.edit') %></b></li>
    </ol>
  </div>
  <div class="col-lg-2"></div>
</div>
<div class="manager-edit-form">
  <%= render 'form' %>
</div>

app/views/manager/discounts/edit_products.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t("manager.layout.#{current_page_name}") %></h2>
    <ol class="breadcrumb">
      <li><%= t("manager.layout.#{current_page_name}") %></li>
      <li><b><%= t('manager.layout.edit') %></b></li>
    </ol>
  </div>
  <div class="col-lg-2"></div>
</div>

<div class="manager-edit-form">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h4>
            <%= link_to manager_discount_path(@discount) do %>
              <i class="fa fa-arrow-left"></i> <%= @discount.title %>
            <% end %>
          </h4>
        </div>
        <div class="ibox-content">
          <div class="table-responsive">
            <%= form_tag update_products_manager_discount_path, method: :put do %>
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th></th>
                    <th></th>
                    <th><%= t 'activerecord.attributes.product.title' %></th>
                    <th class="hidden-xs"><%= t 'activerecord.attributes.product.category' %></th>
                    <th><%= t 'activerecord.attributes.product.price' %></th>
                    <th class="hidden-xs"><%= t 'activerecord.attributes.product.discount' %></th>
                  </tr>
                </thead>
                <tbody>
                  <% @products.each do |product| %>
                    <tr>
                      <td>
                        <% if product.discount and product.discount.id == @discount.id %>
                          <%= check_box_tag "product_ids[]", product.id, checked: true %>
                        <% else %>
                          <%= check_box_tag "product_ids[]", product.id%>
                        <% end %>
                      </td>
                      <td>
                        <%= image_tag default_or_first_image(product), size: 32 %>
                        <% if product.discount and product.discount.id == @discount.id %>
                          <i class = "fa fa-check text-navy"></i>
                        <% end %>
                      </td>
                      <td><%= product.title %></td>
                      <td class="hidden-xs"><%= product.category.title %></td>
                      <td><%= number_to_currency product.price %></td>
                      <td class="hidden-xs"><%= product.discount ? product.discount.title : "-" %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <%= submit_tag t('manager.layout.update'), class: "btn btn-primary pull-right" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/manager/discounts/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-sx-10 col-sm-10 col-md-10 col-lg-10">
    <h2><%= t("manager.layout.#{current_page_name}") %></h2>
    <ol class="breadcrumb">
      <li><%= t("manager.layout.#{current_page_name}") %></li>
      <li><b><%= t('manager.layout.list') %></b></li>
    </ol>
  </div>
  <div class="col-sx-2 col-sm-2 col-md-2 col-lg-2">
    <h2>
      <%= link_to t('manager.layout.new'), new_manager_discount_path, class: "btn btn-primary pull-right" %>
    </h2>
  </div>
</div>

<div class="tabs-container">
  <div class="discounts-list">
    <%= render 'list' %>
  </div>
</div>

app/views/manager/discounts/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t("manager.layout.#{current_page_name}") %></h2>
    <ol class="breadcrumb">
      <li><%= t("manager.layout.#{current_page_name}") %></li>
      <li><b><%= t('manager.layout.new') %></b></li>
    </ol>
  </div>
  <div class="col-lg-2"></div>
</div>

<%= render 'form' %>