config/routes.rb
# Rails.application.routes.default_url_options[:host] = Rails.application.credentials[:development][:hostname]

Rails.application.routes.draw do
  require 'sidekiq/web'
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/  do
    devise_for :managers, path: 'manager',
      controllers: { sessions: 'managers/sessions' },
      path_names: { sign_in: 'login', sign_out: 'logout' }

    namespace :manager do
      authenticate :manager do
        mount Sidekiq::Web => '/sidekiq'
      end
      root 'dashboard#index'
      get :dashboard, to: 'dashboard#index'
      get :chart_statistics, to: 'dashboard#chart_statistics'
      resources :products do
        member do
          get 'change_appearance'
          get 'archive'
          get 'remove_single_image'
        end
        collection do
          get :archival
        end
      end
      resources :orders, only:[:index, :show, :update]
      resources :categories do
        member do
          get 'change_appearance'
        end
      end
      resources :users, only:[:index, :show]
      resources :discounts do
        member do
          get 'change_appearance'
          get 'edit_products'
          put 'update_products'
        end
      end
      resources :contacts, except: [:show]
    end

    root 'store#index', as: 'store'
    resources :line_items, only:[:create, :destroy, :update]
    resources :products, only: [:show]
    get 'category/:category', to: 'products#index', as: 'category_products'

    get   :cart,      to: 'carts#show'
    get   :order,     to: 'orders#new',               as: 'new_order'
    post  :order,     to: 'orders#create',            as: 'orders'
    get   :client,    to: 'users#new',                as: 'new_user'
    post  :client,    to: 'users#create',             as: 'users'
    get   :info,      to: 'user_informations#new',    as: 'new_user_information'
    post  :info,      to: 'user_informations#create', as: 'user_informations'
    get   :contacts,  to: 'store#contacts',           as: 'store_contacts'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/manager/categories_controller.rb
class Manager::CategoriesController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_category_present, only: [:edit, :update, :destroy, :change_appearance]
  before_action :_set_category_orders, only: [:edit, :destroy]
  layout 'managers/dashboard'

  def index
    _set_categories
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new _permitted_category_params

    respond_to do |format|
      if @category.save
        format.html { redirect_to edit_manager_category_path(@category), notice: t('manager.categories.flash.create.success') }
      else
        format.html { render :new }
        flash.now.notice = t('manager.categories.flash.create.failure')
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update _permitted_category_params
        format.html { redirect_to manager_categories_path, notice: t('manager.categories.flash.update.success') }
      else
        format.html { render :edit }
        flash.now.notice = t('manager.categories.flash.update.failure')
      end
    end
  end

  def destroy
    respond_to do |format|
      if @category_orders.empty?
        notice =
          if @category.destroy
            t('manager.categories.flash.destroy.success')
          else
            t('manager.categories.flash.destroy.failure')
          end
        format.html { redirect_to manager_categories_path, notice: notice }
        format.js
      else
        format.html { redirect_to manager_categories_path, notice: t('manager.categories.flash.destroy.involvement') }
      end
    end
  end

  def change_appearance
    respond_to do |format|
      if @category.update visible: !@category.visible
        notice =
          if @category.visible
            t('manager.categories.flash.change_appearance.visible')
          else
            t('manager.categories.flash.change_appearance.invisible')
          end
        format.html { redirect_to manager_categories_path, notice: notice  }
      else
        format.html { redirect_to manager_categories_path, notice: t('manager.categories.flash.change_appearance.failure') }
      end
    end
  end

  private

  def _set_category
    @category = Category.find_by_id params[:id]
  end

  def _ensure_category_present
    redirect_to manager_categories_path unless params[:id].present? && _set_category
  end

  def _set_categories
    @categories = Category.all
  end

  def _set_category_orders
    @category_orders = Order.find(LineItem.where(product_id: @category.products.ids).map(&:order_id))
  end

  def _permitted_category_params
    params.require(:category).permit(:title, :slug, :image, translations_attributes: [:id, :attribute_name, :locale, :value])
  end
end

app/controllers/manager/contacts_controller.rb
class Manager::ContactsController < ApplicationController
  before_action :authenticate_manager!
  before_action :_set_contact, only: [:edit, :update, :destroy, :create]

  layout 'managers/dashboard'

  def index
    @contacts = {}
    Contact.kinds.keys.each { |kind| @contacts[kind] = Contact.public_send kind }
  end

  def new
    @contact = Contact.new
  end

  def edit; end

  def create
    @contact = Contact.new _permitted_contact_params
    respond_to do |format|
      if @contact.save
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.create.success') }
      else
        format.html { render :new }
        flash.now.notice = t('manager.contacts.flash.create.failure')
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update _permitted_contact_params
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.update.success') }
      else
        format.html { render :edit }
        flash.now.notice = t('manager.contacts.flash.update.failure')
      end
    end
  end

  def destroy
    respond_to do |format|
      if @contact.destroy
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.destroy.success') }
      else
        format.html { redirect_to manager_contacts_path, notice: t('manager.contacts.flash.destroy.failure') }
      end
    end
  end

  private

  def _set_contact
    @contact = Contact.find_by_id params[:id]
  end

  def _permitted_contact_params
    params.require(:contact).permit(:kind, :value, :social_type)
  end
end

app/controllers/manager/dashboard_controller.rb
class Manager::DashboardController < ApplicationController
  before_action :authenticate_manager!
  layout 'managers/dashboard'

  def index
    _get_products
    _get_orders
    _get_categories
  end

  def chart_statistics
    render json: { line: SetLineChart.run!, donut: SetDonutChart.run! }
  end

  private

  def _get_products
    outcome = GetScopeStat.run scopes: [:visible, :hidden],
                               model: Product,
                               scope_for_total: :relevant
    @products = outcome.valid? ? outcome.result : nil
  end

  def _get_orders
    outcome = GetScopeStat.run scopes: Order.statuses.keys.map(&:to_sym),
                               model: Order
    @orders = outcome.valid? ? outcome.result : nil
  end

  def _get_categories
    outcome = GetCategoriesStat.run
    @categories = outcome.valid? ? outcome.result : nil
  end

end

app/controllers/manager/discounts_controller.rb
class Manager::DiscountsController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_discount_present, except: [:index, :new, :create]
  layout 'managers/dashboard'

  def index
    @discounts = Discount.all.page params[:page]
  end

  def show; end

  def new
    @discount = Discount.new
  end

  def edit; end

  def create
    @discount = Discount.new _permitted_discount_params
    respond_to do |format|
      if @discount.save
        format.html { redirect_to manager_discounts_path, notice: t('manager.discounts.flash.create.success') }
      else
        flash.now.notice = t('manager.discounts.flash.create.failure')
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @discount.update _permitted_discount_params
        format.html { redirect_to manager_discount_path(@discount), notice: t('manager.discounts.flash.update.success') }
      else
        flash.now.notice = t 'manager.discounts.flash.update.failure'
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @discount.products.blank?
        notice =
          if @discount.destroy
            t('manager.discounts.flash.destroy.success')
          else
            t('manager.discounts.flash.destroy.failure')
          end
        format.html { redirect_to manager_discounts_path, notice: notice }
      else
        format.html { redirect_to manager_discount_path(@discount), notice: t('manager.discounts.flash.destroy.involvement') }
      end
    end
  end

  def change_appearance
    respond_to do |format|
      notice =
        if @discount.actual && @discount.update(start_at: nil, end_at: Time.now)
          t('manager.discounts.flash.change_appearance.invisible')
        elsif !@discount.actual && @discount.update(start_at: nil, end_at: nil)
          t('manager.discounts.flash.change_appearance.visible')
        else
          t('manager.discounts.flash.change_appearance.failure')
        end
      format.html { redirect_to manager_discount_path(@discount), notice: notice }
    end
  end

  def edit_products
    @products = Product.relevant.page params[:page]
  end

  def update_products
    if @discount.products.present?
      Product.where(id: @discount.products.ids - [*params[:product_ids]]).update_all(discount_id: nil)
    end
    Product.where(id: params[:product_ids]).update_all(discount_id: @discount.id)
    redirect_to edit_products_manager_discount_path
  end

  private

  def _ensure_discount_present
    @discount = Discount.find_by(id: params[:id])
    redirect_to manager_discounts_path unless @discount
  end

  def _permitted_discount_params
    params.require(:discount).permit(:title, :description, :value, :start_at, :end_at)
  end
end

app/controllers/manager/orders_controller.rb
class Manager::OrdersController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_order_present, only: [:show, :update]
  layout 'managers/dashboard'

  def index
    if params[:status].present? && Order.statuses.keys.exclude?(params[:status])
      redirect_to manager_orders_path, notice: t('manager.orders.flash.index.prohibited')
    else
      @current_status = params[:status]
      @orders = Order.filter(_filtering_params)
                     .search_by_name_or_email_or_telephone(params[:search_query])
                     .page params[:page]
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def show; end

  def update
    respond_to do |format|
      if @order.update _permitted_order_params
        OrderMailer.manager_information(@order).deliver
        OrderMailer.client_confirmation(@order).deliver if params[:notification]
        format.html do
          redirect_to manager_orders_path(status: _permitted_order_params[:status]),
                      notice: t('manager.orders.flash.update.success')
        end
      else
        flash.now.notice = t('manager.orders.flash.update.failure')
        format.html { render :edit }
      end
    end
  end

  private

  def _ensure_order_present
    @order = Order.includes(:products).find_by(id: params[:id])
    redirect_to manager_order_path unless @order
  end

  def _permitted_order_params
    params.require(:order).permit(:title, :description, :image, :price, :status)
  end

  def _filtering_params
    params.slice(:status)
  end

end

app/controllers/manager/users_controller.rb
class Manager::UsersController < ApplicationController
  before_action :authenticate_manager!
  layout 'managers/dashboard'

  def index
    @users = User.search_by_name_or_email_or_telephone(params[:search_query]).page params[:page]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    redirect_to users_path unless @user
  end

end

app/controllers/managers/confirmations_controller.rb
class Managers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/managers/omniauth_callbacks_controller.rb
class Managers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/managers/passwords_controller.rb
class Managers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/managers/sessions_controller.rb
class Managers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'managers/manager'
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    if current_manager
      redirect_to manager_dashboard_path
      flash[:notice] = I18n.t('devise.sessions.signed_in')
    else
      flash[:error] = I18n.t('devise.sessions.error')
      redirect_to new_manager_session_path
    end
  end

  # DELETE /resource/sign_out
  def destroy
    return unless sign_out(current_manager)
    redirect_to new_manager_session_path
    flash[:notice] = I18n.t('devise.sessions.signed_out')
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/manager_helper.rb
module ManagerHelper

  def current_page_name
    controller.controller_name.split("_").join(" ")
  end

  def nav_link link_text, link_path, icons_class = '', method = :get
    class_name = current_page?(link_path) ? 'active' : ''
    link_class = icons_class.blank? ? '' : 'nav-label'
    content_tag :li, class: class_name do
      concat (
        link_to link_path, method: method do
          concat content_tag :i, '', class: icons_class if icons_class.present?
          concat content_tag :span, link_text, class: link_class
        end
      )
    end
  end

  def group_link link_text, controller, icons_class, &block
    class_name = params[:controller].delete('/').start_with?(controller.delete('/')) ? 'active' : ''
    content_tag :li, class: class_name do
      concat (
        link_to url_for(controller: controller, action: 'index') do
          concat content_tag :i, '', class: icons_class
          concat content_tag :span, link_text, class: 'nav-label'
          concat content_tag :span, '', class: 'fa arrow'
        end
      )
      block.call if block_given?
    end
  end

  def orders_status_links
    links_hash = {}
    Order.statuses.keys.each { |status| links_hash[status] = manager_orders_path(status: status) }
    links_hash
  end

  def pending_orders_counter
    Order.where(status: 'pending').count
  end


  def collapse_button button_title, button_class, target_id, target, &block
    concat button_tag button_title, class: button_class, data: { toggle: "collapse", target: "##{target_id}" }
    concat content_tag :br
    content_tag :ul, id: target_id, class: "list-group collapse" do
      target.each do |item|
        concat (
          content_tag :li, class: "list-group-item" do
            yield item
          end
        )
      end
    end
  end

  def time_delay created_at
    time_ago_in_words(Time.now - (Time.now - created_at.to_time).seconds)
  end
end

app/views/manager/contacts/_form.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= t 'activerecord.errors.messages.record_invalid', errors: @contact.errors.count %></h2>
    <ul>
    <% @contact.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:manager, @contact] do |form| %>
  <div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="row">
      <div class="col-lg-12">
        <div class="ibox contact-detail">
          <div class="ibox-content">
            <fieldset class="form-horizontal">
              <% if @contact.social? %>
                <div class="form-group">
                  <%= form.label :kind, class:"col-sm-2 col-lg-1 control-label" %>
                  <div class="col-sm-10 col-lg-11">
                    <%= form.select :kind,
                      Contact.kinds.keys.map{ |key| [t("activerecord.attributes.contact.kinds.#{key}"), key]},
                      { },
                      { class: "form-control m-b" } %>
                  </div>
                </div>
              <% end %>

              <div class="form-group">
                <%= form.label :social_type, class:"col-sm-2 col-lg-1 control-label" %>
                <div class="col-sm-10 col-lg-11">
                  <%= form.select :social_type,
                    Contact.social_types.keys.map{ |key| [key.capitalize, key ]},
                    { include_blank: t('manager.layout.none') },
                    { class:"form-control m-b"} %>
                </div>
              </div>

              <div class="form-group">
                <%= form.label :value, class:"col-sm-2 col-lg-1 control-label" %>
                <div class="col-sm-10 col-lg-11">
                  <%= form.text_field :value,
                    placeholder: t('activerecord.attributes.contact.value'),
                    class: "form-control",
                    required: true %>
                </div>
              </div>


            </fieldset>

            <br>

            <div class="row">
              <div class="col-lg-12">
                <div class="form-group">
                  <%= form.submit class: "btn btn-primary pull-right" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/manager/contacts/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t("manager.layout.#{current_page_name}") %></h2>
    <ol class="breadcrumb">
      <li>
        <%= t("manager.layout.#{current_page_name}") %>
      </li>
      <li>
        <b><%= t('manager.layout.edit') %></b>
      </li>
    </ol>
  </div>
  <div class="col-lg-2"></div>
</div>
<div class="manager-edit-form">
  <%= render 'form' %>
</div>

app/views/manager/contacts/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">

    <h2><%= t "manager.layout.#{current_page_name}" %></h2>

    <ol class="breadcrumb">
      <li><%= t "manager.layout.#{current_page_name}" %></li>
      <li>
        <b><%= t 'manager.layout.list' %></b>
      </li>
    </ol>
  </div>
  <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
    <h2>
      <%= link_to t('manager.layout.new'), new_manager_contact_path,
        class: "btn btn-primary pull-right" %>
      </h2>
  </div>
</div>

<div class="wrapper wrapper-content">
  <table class="table">
    <% @contacts.each do |key, value| %>
      <tr>
        <td colspan="3">
          <h2><%= t("activerecord.attributes.contact.kinds.#{key}") %></h2>
        </td>
      </tr>
      <% value.each do |contact| %>
        <tr class="white-bg">
          <td class="text-center">
            <% if contact.social? %>
              <%= content_tag(:i, class:"fa fa-#{Contact.social_types[contact.social_type]}"){}  %>
            <% else %>
              <%= content_tag(:i, class:"fa fa-#{Contact.kinds[contact.kind]}"){} %>
            <% end %>
          </td>
          <td><%= contact.value %></td>
          <td class="text-center">
            <%= link_to edit_manager_contact_path(contact) do %>
              <i class="fa fa-pencil-square"></i>
            <% end %>
            <%= link_to manager_contact_path(contact), method: :delete do %>
              <i class="fa fa-trash-o"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/manager/contacts/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2><%= t "manager.layout.#{current_page_name}" %></h2>
    <ol class="breadcrumb">
      <li>
        <%= t "manager.layout.#{current_page_name}" %>
      </li>
      <li>
        <b><%= t 'manager.layout.new' %></b>
      </li>
    </ol>
  </div>
  <div class="col-lg-2"></div>
</div>

<%= render 'form', contact: @contact %>