config/routes.rb
# Rails.application.routes.default_url_options[:host] = Rails.application.credentials[:development][:hostname]

Rails.application.routes.draw do
  require 'sidekiq/web'
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/  do
    devise_for :managers, path: 'manager',
      controllers: { sessions: 'managers/sessions' },
      path_names: { sign_in: 'login', sign_out: 'logout' }

    namespace :manager do
      authenticate :manager do
        mount Sidekiq::Web => '/sidekiq'
      end
      root 'dashboard#index'
      get :dashboard, to: 'dashboard#index'
      get :chart_statistics, to: 'dashboard#chart_statistics'
      resources :products do
        member do
          get 'change_appearance'
          get 'archive'
          get 'remove_single_image'
        end
        collection do
          get :archival
        end
      end
      resources :orders, only:[:index, :show, :update]
      resources :categories do
        member do
          get 'change_appearance'
        end
      end
      resources :users, only:[:index, :show]
      resources :discounts do
        member do
          get 'change_appearance'
          get 'edit_products'
          put 'update_products'
        end
      end
      resources :contacts, except: [:show]
    end

    root 'store#index', as: 'store'
    resources :line_items, only:[:create, :destroy, :update]
    resources :products, only: [:show]
    get 'category/:category', to: 'products#index', as: 'category_products'

    get   :cart,      to: 'carts#show'
    get   :order,     to: 'orders#new',               as: 'new_order'
    post  :order,     to: 'orders#create',            as: 'orders'
    get   :client,    to: 'users#new',                as: 'new_user'
    post  :client,    to: 'users#create',             as: 'users'
    get   :info,      to: 'user_informations#new',    as: 'new_user_information'
    post  :info,      to: 'user_informations#create', as: 'user_informations'
    get   :contacts,  to: 'store#contacts',           as: 'store_contacts'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < StoreController
  before_action :_set_cart_variables, :_set_categories

  def show; end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_table.html.erb
<% @cart.line_items.each do |line_item| %>
  <div class="row">
<!-- Mobie version -->
    <div class="row visible-xs">
      <div class="col-xs-4 cart-mobile-image">
        <%= link_to product_path(line_item.product) do %>
          <%= image_tag default_or_first_image(line_item.product),  class:'img-responsive'%>
        <% end %>
      </div>
      <div class="col-xs-8">
        <div class="row">
          <div class="col-xs-9 cart-mobile-title">
            <strong><%= line_item.product.title %></strong>
          </div>
          <div class="col-xs-3 cart-mobile-delete">
            <%= link_to line_item_path(line_item), method: "delete", remote: true do  %>
              <i class="material-icons pull-right">close</i>
            <% end  %>
          </div>
        </div>
        <div class="row cart-mobile-quantity pull-left">
          <% if line_item.quantity > 1 %>
            <div class="col-xs-4 text-center">
              <%= link_to line_item_path(line_item,
                line_item:{ quantity: "#{line_item.quantity - 1}" }),
                method: :put,
                remote: true, class: "minus-button" do  %>
                  <i class="material-icons">remove</i>
              <% end  %>
            </div>
          <% else %>
            <div class="col-xs-4 text-center">
              <i class="material-icons">remove</i>
            </div>
          <% end %>
          <div class="col-xs-4 text-center">
            <span><strong><%= line_item.quantity %></strong></span>
          </div>
          <div class="col-xs-4 text-center">
            <%= link_to line_item_path(line_item,
              line_item:{ quantity: "#{line_item.quantity + 1}" }),
              method: :put,
              remote: true,
              class: "plus-button" do  %>
                <i class="material-icons">add</i>
            <% end  %>
          </div>
        </div>
        <div class="row cart-monile-size">
            <div class="col-xs-12">
              <%= t 'carts.show.size' %>: <%= line_item.size.values.join(" & ")  if line_item.size.present? %>
            </div>
        </div>
        <div class="row cart-mobile-price">
          <div class="col-xs-12">
            <% if line_item.product.discount and line_item.product.discount.actual %>
              <span><%= number_to_currency line_item.product.discount_price %></span>
              <span class="old-price"><%= number_to_currency line_item.product.price %></span>
            <% else %>
              <span><%= number_to_currency line_item.product.price  %></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>

<!-- Other versions -->
    <table class="hidden-xs">
      <tr>
        <td class="col-sm-2 col-md-2 col-lg-2 cart-image" valign="middle">
          <%= link_to product_path(line_item.product) do %>
            <%= image_tag default_or_first_image(line_item.product), class:'img-responsive' %>
          <% end %>
        </td>
        <td class="col-sm-3 col-md-3 col-lg-3" valign="middle">
          <strong><%= line_item.product.title %></strong>
        </td>
        <td class="col-sm-2 col-md-2 col-lg-2 cart-quantity" valign="middle">
          <div class="row">
            <% if line_item.quantity > 1 %>
              <div class="col-sm-4 col-md-4 col-lg-4 text-center">
                <%= link_to line_item_path(line_item,
                  line_item:{ quantity: "#{line_item.quantity - 1}" }),
                  method: :put,
                  remote: true,
                  class: "minus-button" do  %>
                    <i class="material-icons">remove</i>
                <% end  %>
              </div>
            <% else %>
              <div class="col-sm-4 col-md-4 col-lg-4 text-center">
                <i class="material-icons">remove</i>
              </div>
            <% end %>
            <div class="col-sm-4 col-md-4 col-lg-4 text-center">
              <span><strong><%= line_item.quantity %></strong></span>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 text-center">
              <%= link_to line_item_path(line_item,
                line_item:{ quantity: "#{line_item.quantity + 1}" }),
                method: :put,
                remote: true,
                class: "plus-button" do  %>
                  <i class="material-icons">add</i>
              <% end  %>
            </div>
          </div>
        </td>
        <td class="col-sm-2 col-md-2 col-lg-2 cart-size" valign="middle">
          <%= t 'carts.show.size' %>: <%= line_item.size.values.join(" & ")  if line_item.size.present? %>
        </td>
        <td class="col-sm-2 col-md-2 col-lg-2 cart-price">
          <% if line_item.product.discount and line_item.product.discount.actual %>
            <%= number_to_currency line_item.product.discount_price %>
            <span class="old-price"><%= number_to_currency line_item.product.price %></span>
          <% else %>
            <%= number_to_currency line_item.product.price %>
          <% end %>
        </td>
        <td class="col-sm-1 col-md-1 col-lg-1 cart-delete" valign="middle">
          <%= link_to line_item_path(line_item), method: "delete", remote: true do  %>
            <i class="material-icons">close</i>
          <% end  %>
        </td>
      </tr>
    </table>
  </div>
<% end %>

app/views/carts/_cart_total_amount.html.erb
<span class="pull-right">
  <strong><%= t('carts.show.total')  %>:
  <%= number_to_currency @total %>
  </strong>
</span>

app/views/carts/_empty_cart.html.erb
<div class="cart-headline text-center">
  <br>
  <span>
    <%= t('carts.show.your') %>
    <i class="material-icons md-24">shopping_cart</i>
    <%= t 'carts.show.is_empty' %>
  </span>
</div>
<div class="row text-center">
  <%= link_to t('carts.show.back_shoping'), store_path,  class:"material-button" %>
</div>

app/views/carts/_line_items_count.html.erb
<%= @cart.line_items.count %> <%= t 'carts.show.item', count: @cart.line_items.count %>

app/views/carts/show.html.erb
<div class="container cart-container">
  <% if @cart.line_items.any? %>
    <div class="full-cart">
      <div class="cart-headline text-center">
        <h2><%= t '.your_cart'  %></h2>
          <span id="line-items-count">
            <%= render 'line_items_count' %>
          </span>
      </div>
      <div class="container cart-table" id="cart-table">
        <%= render 'cart_table' %>
      </div>
      <div class="container checkout-box hidden-xs">
        <div class="row">
          <div class="col-sm-9 col-md-9 col-xl-9 cart-total-amount">
            <%= render 'cart_total_amount' %>
          </div>
          <div class="col-sm-3 col-md-3 col-xl-3">
            <%= link_to t('.checkout'), new_order_path, class:"material-button" %>
          </div>
        </div>
      </div>
      <div class="container checkout-box visible-xs">
        <div class="row">
          <div class="col-xs-12 cart-total-amount">
            <%= render 'cart_total_amount' %>
          </div>
        </div>
        <br>
        <br>
        <div class="row text-center">
          <div class="col-xs-12">
            <%= link_to t('.checkout'), new_order_path, class:"material-button" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="empty-cart">
    <%= render 'empty_cart' if @cart.line_items.empty?  %>
  </div>
</div>