config/routes.rb
# Rails.application.routes.default_url_options[:host] = Rails.application.credentials[:development][:hostname]

Rails.application.routes.draw do
  require 'sidekiq/web'
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/  do
    devise_for :managers, path: 'manager',
      controllers: { sessions: 'managers/sessions' },
      path_names: { sign_in: 'login', sign_out: 'logout' }

    namespace :manager do
      authenticate :manager do
        mount Sidekiq::Web => '/sidekiq'
      end
      root 'dashboard#index'
      get :dashboard, to: 'dashboard#index'
      get :chart_statistics, to: 'dashboard#chart_statistics'
      resources :products do
        member do
          get 'change_appearance'
          get 'archive'
          get 'remove_single_image'
        end
        collection do
          get :archival
        end
      end
      resources :orders, only:[:index, :show, :update]
      resources :categories do
        member do
          get 'change_appearance'
        end
      end
      resources :users, only:[:index, :show]
      resources :discounts do
        member do
          get 'change_appearance'
          get 'edit_products'
          put 'update_products'
        end
      end
      resources :contacts, except: [:show]
    end

    root 'store#index', as: 'store'
    resources :line_items, only:[:create, :destroy, :update]
    resources :products, only: [:show]
    get 'category/:category', to: 'products#index', as: 'category_products'

    get   :cart,      to: 'carts#show'
    get   :order,     to: 'orders#new',               as: 'new_order'
    post  :order,     to: 'orders#create',            as: 'orders'
    get   :client,    to: 'users#new',                as: 'new_user'
    post  :client,    to: 'users#create',             as: 'users'
    get   :info,      to: 'user_informations#new',    as: 'new_user_information'
    post  :info,      to: 'user_informations#create', as: 'user_informations'
    get   :contacts,  to: 'store#contacts',           as: 'store_contacts'
  end
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}"), constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" }
  get '', to: redirect("/#{I18n.default_locale}")
end

app/models/product.rb
class Product < ApplicationRecord
  TRANSLATEABLE_ATTRBUTES = [:title, :description].freeze

  include Filterable
  include Translateable
  translate TRANSLATEABLE_ATTRBUTES

  mount_uploaders :images, ProductImageUploader

  enum size: { standard: %w[XS S M L XL],
               bra:      %w[70A 70B 70C 75A 75B 75C 75D 80B 80C 85B 85C] }
  enum priority: { hi: 1, mid: 2, low: 3 }

  has_many :line_items
  has_many :orders, through: :line_items
  has_many :translations, as: :translateable
  belongs_to :category
  belongs_to :discount, optional: true

  validates :title, :description, :category, :sizes, presence: true
  validates :price, numericality: {
    greater_than_or_equal_to: 0.01,
    message: I18n.translate('activerecord.errors.messages.invalid_price')
  }
  # Client scopes
  default_scope { includes(:translations).order priority: :asc }
  scope :shown,             -> { where archive: false, visible: true, category_id: Category.visible.ids }
  scope :by_category,       ->(category_id) { where category_id: category_id, archive: false, visible: true }
  # Manager scopes
  scope :relevant,          -> { where(archive: false).reorder created_at: :desc }
  scope :archival,          -> { where(archive: true).reorder created_at: :desc }
  scope :visible,           -> { where(archive: false, visible: true).reorder created_at: :desc }
  scope :hidden,            -> { where(archive: false, visible: false).reorder created_at: :desc }
  scope :manager_category,  ->(category_id) { where(category_id: category_id, archive: false).reorder created_at: :desc }
  # Filterable scopes
  scope :filter_relevant,          ->(_) { where(archive: false).reorder created_at: :desc }
  scope :filter_archival,          ->(_) { where(archive: true).reorder created_at: :desc }
  scope :filter_visible,           ->(_) { where(archive: false, visible: true).reorder created_at: :desc }
  scope :filter_hidden,            ->(_) { where(archive: false, visible: false).reorder created_at: :desc }
  scope :filter_shown,             ->(_) { where archive: false, visible: true, category_id: Category.visible.ids }
  scope :filter_by_category,       ->(category_id) { where category_id: category_id, archive: false, visible: true }
  scope :filter_manager_category,  ->(category_id) { where(category_id: category_id, archive: false).reorder created_at: :desc }

  accepts_nested_attributes_for :translations, reject_if: :all_blank

  after_create :add_translations

  def discount_price
    if discount.present? && discount.actual
      (price * (1 - discount.value * 0.01)).round(2)
    else
      price
    end
  end
end

app/controllers/api/v1/products_controller.rb
module Api
  module V1
    class ProductsController < ApplicationController
      def index
        unless params[:category].present? and _set_category and @current_category.visible
          @success = false
          @outcome = { warning: "Can't find products of the category" }
        else
          @success = true
          @outcome = {
            category: @current_category,
            products: Product.shown.by_category(@current_category.id).page(params[:page]),
            count: Product.shown.by_category(@current_category.id).count
          }
        end
        _render_response
      end


      def show
        unless params[:id].present? and _set_product and _set_product_category.visible
          @success = false
          @outcome = { warning: "Can't find product" }
        else
          @success = true
          @outcome = {
            categorySlug: @category.slug,
            product: @product,
          }
        end
        _render_response
      end

    private
      def _render_response
        render json: @outcome, status: @success ? :ok : :unprocessable_entity
      end

      def _set_category
        @current_category = FetchCategory.run!(category_parameter: params[:category])
      end

      def _set_product
        @product = Product.find_by_id params[:id]
      end

      def _set_product_category
        @category = @product.category
      end

    end
  end
end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ApplicationController
  before_action :authenticate_manager!
  before_action :_ensure_product_present, except: [:index, :archival, :new, :create]
  before_action :_set_product_orders, only: :destroy

  layout 'managers/dashboard'

  def index
    _set_categories
    _fetch_current_category if params[:manager_category].present?
    @products = Product.relevant.filter(params.slice(:visible, :hidden, :manager_category)).page params[:page]
    respond_to do |format|
      format.html
      format.js
    end
  end

  def archival
    @products = Product.archival.page params[:page]
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new _permitted_product_params
    respond_to do |format|
      if @product.save
        _add_more_images if _permitted_product_images_params.present?
        format.html { redirect_to edit_manager_product_path(@product), notice: t('manager.products.flash.create.success') }
      else
        format.html { render :new }
        flash.now.notice = t('manager.products.flash.create.failure')
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update _permitted_product_params
        _add_more_images if _permitted_product_images_params.present?
        format.html { redirect_to manager_product_path(@product), notice: t('manager.products.flash.update.success') }
      else
        flash.now.notice = t('manager.products.flash.update.failure')
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @product_orders.blank?
        notice =
          if @product.destroy
            t('manager.products.flash.destroy.success')
          else
            t('manager.products.flash.destroy.failure')
          end
        format.html { redirect_to archival_manager_products_path, notice: notice }
      else
        format.html { redirect_to archival_manager_products_path, notice: t('manager.products.flash.destroy.involvement') }
      end
    end
  end

  def archive
    respond_to do |format|
      notice =
        if @product.update(archive: !@product.archive, visible: false)
          if @product.archive
            t('manager.products.flash.archive.archived')
          else
            t('manager.products.flash.archive.restored')
          end
        else
          t('manager.products.flash.archive.failure')
        end
      format.html { redirect_to (@product.archive ? manager_products_path : archival_manager_products_path), notice: notice }
    end
  end

  def change_appearance
    respond_to do |format|
      notice =
        if @product.update(visible: !@product.visible)
          if @product.visible
            t('manager.products.flash.appearance.visible')
          else
            t('manager.products.flash.appearance.invisible')
          end
        else
          t('manager.products.flash.change_appearance.failure')
        end
      format.html { redirect_to manager_products_path, notice: notice }
    end
  end

  def remove_single_image
    respond_to do |format|
      notice =
        if @product.update(images: @product.images.tap { |a| a.delete_at(params[:index].to_i) })
          t('manager.products.flash.remove_single_image.success')
        else
          t('manager.products.flash.remove_single_image.failure')
        end
      format.html { redirect_to edit_manager_product_path(@product), notice: notice }
      format.js
    end
  end

  private

  def _ensure_product_present
    @product = Product.find_by(id: params[:id])
    redirect_to manager_order_path unless @product
  end

  def _permitted_product_params
    params.require(:product).permit :title,
                                    :description,
                                    :price,
                                    :priority,
                                    :index,
                                    :category_id,
                                    sizes: [bra: [], panties: [], standard: []],
                                    translations_attributes: [:id, :attribute_name, :locale, :value]
  end

  def _permitted_product_images_params
    params.require(:product).permit(images: [])
  end

  def _add_more_images
    @product.update images: (@product.images + _permitted_product_images_params[:images])
  end

  def _set_product_orders
    @product_orders = Order.find(LineItem.where(product_id: @product.id).pluck(:order_id))
  end

  def _fetch_current_category
    @current_category = Category.find_by(id: params[:manager_category])
  end

  def _set_categories
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < StoreController
  before_action :_set_cart_variables, :_set_categories

  def index
    if params[:category].present? && _set_category && @current_category.visible
      @products = Product.shown.by_category(@current_category.id).page(params[:page])
    else
      redirect_to store_path, notice: t('products.flash.index.missing_category')
    end
  end

  def show
    if _set_product && @product.visible && @product.category.visible
      @current_category = @product.category
    else
      redirect_to store_path, notice: t('products.flash.show.missing_product')
    end
  end

  private

  def _set_product
    @product = Product.find_by(id: params[:id])
  end

  def _set_category
    @current_category = Category.find_by(slug: params[:category])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_categories.html.erb
<div class="app-toolbar hidden-xs">
  <ul class="material-tabs">
    <% @categories.each do |category| %>
      <%= content_tag :li, class: "#{ category == @current_category ? 'active' : '' }" do  %>
        <%= link_to category.title, category_products_path(category: category.slug ) %>
      <% end %>
    <% end  %>
  </ul>
</div>

app/views/products/_images_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <% content_tag :ol, class:"carousel-indicators" do  %>
    <% @product.images.count.times do |time| %>
      <% if time == 0 %>
        <%= content_tag :li, data: { target: "#myCarousel", slide_to: time }, class:"active" %>
      <% else %>
        <%= content_tag :li, data: { target: "#myCarousel", slide_to: time } %>
      <% end %>
    <% end %>
  <% end %>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @product.images.each_with_index do |image, index| %>
      <% if index == 0 %>
        <%= content_tag :div, class:"item active" do %>
          <%= image_tag image.url, alt: @product.title, id: "myImg" %>
        <% end %>
      <% else %>
        <%= content_tag :div, class:"item" do %>
          <%= image_tag image.url, alt: @product.title %>
        <% end %>
      <% end %>
    <% end %>
  </div>

  <!-- Left and right controls -->
  <% if  @product.images.count > 1 %>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  <% end %>
</div>


<!-- The Modal -->
<div id="product-image-modal" class="modal">

  <!-- The Close Button -->
  <span class="close">&times;</span>

  <!-- Modal Content (The Image) -->
  <img class="modal-content" id="full-screen-image">

  <!-- Modal Caption (Image Text) -->
  <div id="caption"></div>
</div>

app/views/products/_product.html.erb
<div class="oriented">
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4">
    <%= link_to product_path(product) do %>
      <div class="product-basic">
        <div class="product-image">
          <% if product.discount and product.discount.actual  %>
            <span class="discount-value">-<%= number_to_percentage(product.discount.value, precision: 0) %></span>
          <% end %>
          <%= image_tag default_or_first_image(product), class: "img-responsive" %>
        </div>

        <div class="product-title text-center">
          <%= product.title %>
        </div>
        <% if product.discount and product.discount.actual %>
          <div class="product-price-discount">
            <span class="old"><%= number_to_currency product.price %></span>
            <span class="new"><%= number_to_currency product.discount_price %></span>
          </div>
        <% else %>
          <div class="product-price">
            <%= number_to_currency product.price%>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<%= render partial: "categories" %>

<div class="category-headline content">
  <%= image_tag category_image(@current_category.image), class: "hidden-xs" %>
  <h2> <%= @current_category.title %> </h2>
  <span>(<%= @products.total_count %> <%= t '.item', count: @products.total_count %>)</span>
</div>

<div class="container products">
  <div class="row">
    <% @products.each do |product| %>
      <%= render partial: "product", locals: { product: product } %>
    <% end %>
  </div>
</div>

<div class="text-center">
  <%= paginate @products %>
</div>
<footer class="footer">
  <div class="app-toolbar">
    <ul class="material-tabs">
      <li><div class="footer-tab"><%= link_to t('contacts'), store_contacts_path %></div></li>
    </ul>
  </div>
</footer>

app/views/products/show.html.erb
<%= render partial: "categories" %>

<div class="container">
  <%= form_for :line_item, url: line_items_path, remote: true  do |f| %>
  <div class="oriented">
    <div class="row product-detailed">
      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <div class="product-detailed-images">
          <%= render 'images_carousel'%>
        </div>
      </div>

      <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 product-detailed-details oriented">
        <h1><%= @product.title %></h1>
        <% if @product.discount and @product.discount.actual %>
        <div class="product-details-price-discount">
          <span class="old"><%= number_to_currency @product.price %></span>
          <span class="new"><%= number_to_currency @product.discount_price %></span>
        </div>
        <% else %>
          <div class="product-details-price">
            <%= number_to_currency @product.price %>
          </div>
        <% end %>

        <%= f.fields_for :size do |ff| %>
          <% @product.sizes.each do |key,value| %>
            <% if @product.sizes[key].present? %>
              <%= ff.label "#{t "products.show.#{key}"} #{t 'products.show.size'}" %>
              <%= ff.select key, ( key.downcase == "bra" ? @product.sizes[key].sort : Product.sizes[:standard] & @product.sizes[key]), {}, { class: "material-select" } %>
            <% end %>
          <% end %>
        <% end %>
        <%= f.hidden_field :product_id, value: @product.id   %>

        <div class="product-detailed-description">
          <h2><%= t '.description' %></h2>
          <p><%= @product.description %></p>
        </div>
      </div>
    </div>

    <div class="add-to-cart-btn">
      <%= f.submit "#{t '.add_to_cart'}", class: "material-button" %>
    </div>
  </div>
  <% end %>
</div>